import React, { useState } from "react";

const AddMaterial = () => {
  // State to hold the name entered by the user for the material
  const [materialName, setMaterialName] = useState("");
  // State to store the list of all saved materials
  // Each material object will have an id and a name
  const [savedMaterials, setSavedMaterials] = useState([]);
  // State for alert messages (instead of window.alert)
  const [message, setMessage] = useState({ text: "", type: "" });

  // Handles the change in the material name input
  const handleMaterialNameChange = (e) => {
    setMaterialName(e.target.value);
  };

  // Handles adding a new material to the savedMaterials list
  const handleAddMaterial = () => {
    if (!materialName.trim()) {
      setMessage({ text: "Please enter a material name.", type: "error" });
      return;
    }

    // Auto-generate a smaller, unique-enough ID for the material
    // Combines timestamp and a small random string for uniqueness
    const autoGeneratedId =
      Date.now().toString(36) + Math.random().toString(36).substring(2, 5);

    const newMaterial = {
      id: autoGeneratedId, // Use auto-generated ID
      name: materialName.trim(),
    };

    setSavedMaterials((prevMaterials) => [...prevMaterials, newMaterial]);
    setMaterialName(""); // Clear the material name field after adding
    setMessage({ text: "Material added successfully!", type: "success" });
    setTimeout(() => setMessage({ text: "", type: "" }), 3000); // Clear message after 3 seconds
  };

  // Handles removing a material from the savedMaterials list
  const handleRemoveMaterial = (idToRemove) => {
    setSavedMaterials((prevMaterials) =>
      prevMaterials.filter((material) => material.id !== idToRemove)
    );
    setMessage({ text: "Material removed.", type: "info" });
    setTimeout(() => setMessage({ text: "", type: "" }), 3000); // Clear message after 3 seconds
  };

  return (
    <div className="bg-white p-4 sm:p-6 lg:p-8 overflow-y-auto min-h-screen">
      <div className="max-w-7xl mx-auto">
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-300">
          <h1 className="text-lg font-medium mb-6 whitespace-nowrap">
            Add New Material
          </h1>

          <div className="space-y-6 text-sm p-4 border border-gray-300 rounded-lg bg-gray-50 mb-8">
            <h2 className="font-medium text-gray-700">Enter Material Name</h2>

            {/* Message Box */}
            {message.text && (
              <div
                className={`p-3 rounded-md text-white text-center 
              ${
                message.type === "error"
                  ? "bg-red-500"
                  : message.type === "success"
                  ? "bg-green-500"
                  : "bg-blue-500"
              }`}
              >
                {message.text}
              </div>
            )}

            {/* Material Name Input */}
            <div>
              <label
                htmlFor="materialName"
                className="block mb-2 whitespace-nowrap"
              >
                Material Name
              </label>
              <input
                type="text"
                id="materialName"
                value={materialName}
                onChange={handleMaterialNameChange}
                placeholder="e.g., Cotton, Plastic, Wood"
                className="border border-gray-300 rounded-md p-2 w-full focus:ring-blue-500 focus:border-blue-500"
              />
            </div>

            {/* Add Material Button */}
            <button
              type="button"
              onClick={handleAddMaterial}
              className="bg-blue-600 text-white px-6 py-2 rounded-md whitespace-nowrap hover:bg-blue-700 transition-colors duration-200 shadow-md"
            >
              Add Material
            </button>
          </div>

          {/* Saved Materials Table */}
          {savedMaterials.length > 0 && (
            <div className="mt-8 p-4 border border-gray-300 rounded-lg bg-gray-50 shadow-sm">
              <h2 className="font-medium text-gray-700 mb-4">
                Saved Materials
              </h2>
              <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-200">
                  <thead className="bg-gray-100">
                    <tr>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider rounded-tl-lg">
                        ID
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Name
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider rounded-tr-lg">
                        Actions
                      </th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {savedMaterials.map((material) => (
                      <tr key={material.id}>
                        <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                          {material.id}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-700">
                          {material.name}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                          <button
                            onClick={() => handleRemoveMaterial(material.id)}
                            className="text-red-600 hover:text-red-900 transition-colors duration-200"
                          >
                            Remove
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AddMaterial;
